name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 mypy pytest pytest-asyncio asgi-lifespan

      - name: Lint with flake8
        run: |
          source .venv/bin/activate
          flake8 .

      - name: Check code formatting with black
        run: |
          source .venv/bin/activate
          black --check .

      - name: Type check with mypy
        run: |
          source .venv/bin/activate
          mypy .

      - name: Run tests with pytest
        run: |
          source .venv/bin/activate
          pytest -v